<a href="https://colab.research.google.com/github/hungnguyen-165/Programming/blob/main/week_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
# Creating a Series
series = pd.Series([1, 2, 3])
# Creating a DataFrame
dataframe = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})

dataframe.groupby('Name')['Age'].mean()

Name
Alice    25.0
Bob      30.0
Name: Age, dtype: float64

In [16]:
from types import new_class
import pandas as pd  # pd is a common shortcut name

# TODO: Create a dictionary of lists
data = {
    'Month': ['January', 'February', 'March'],
    'Product A': [120, 134, 145],
    'Product B': [90, 100, 110],
    'Product C': [140, 150, 160]
}

# TODO: Convert to a DataFrame
df = pd.DataFrame(data)
# update month and data
new_data = ({
    'Month': ['April', 'May', 'June'],
    'Product A': [210, 140, 120],
    'Product B': [230, 140, 190],
    'Product C': [240, 150, 100]
})
new_df = pd.DataFrame(new_data)
# Concatenate the two DataFrames
df = pd.concat([df, new_df], ignore_index=True)

# total values
df['Total'] = df.iloc[:, 1:].sum(axis=1)

# Average values
df['Average'] = df.iloc[:, 1:4].mean(axis=1).round(2)
# Show the table
df

      Month  Product A  Product B  Product C  Total  Average
0   January        120         90        140    350   116.67
1  February        134        100        150    384   128.00
2     March        145        110        160    415   138.33
3     April        210        230        240    680   226.67
4       May        140        140        150    430   143.33
5      June        120        190        100    410   136.67

In [21]:
import pandas as pd

df = pd.read_csv('sales_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        10000 non-null  object
 1   store_id    10000 non-null  int64
 2   product_id  10000 non-null  int64
 3   units_sold  9700 non-null   float64
 4   unit_price  9700 non-null   float64
 5   sales       10000 non-null  float64
dtypes: float64(3), int64(2), object(1)
memory usage: 468.9+ KB

In [22]:
df.describe()

           store_id    product_id   units_sold   unit_price         sales
count  10000.000000  10000.000000  9700.000000  9700.000000  10000.000000
mean    1004.455800    249.183200    19.982784    25.078123    544.512962
std        2.899877     28.972314     4.472414     4.951588    466.388013
min     1000.000000    200.000000     6.000000     6.090000    103.180000
25%     1002.000000    224.000000    17.000000    21.740000    393.582500
50%     1004.000000    249.000000    20.000000    25.100000    492.015000
75%     1007.000000    274.000000    23.000000    28.450000    600.865000
max     1009.000000    299.000000    38.000000    46.010000   7763.300000

In [23]:
df_clean = df.dropna()

print("Original rows: ", len(df))
print("Cleaned rows: ", len(df_clean))

Original rows:  10000
Cleaned rows:  9410

In [24]:
# Step-by-step: calculate bounds
Q1 = df_clean['sales'].quantile(0.25)
Q3 = df_clean['sales'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Lower bound: 81.40750000000003
Upper bound: 911.9475

In [25]:
# Filter out rows outside the bounds
df_filtered = df_clean[(df_clean['sales'] >= lower_bound) & (df_clean['sales'] <= upper_bound)]

print("Rows before filtering:", len(df_clean))
print("Rows after filtering:", len(df_filtered))

# Preview final cleaned data
df_filtered.head()

Rows before filtering: 9410
Rows after filtering: 9223

         date  store_id  product_id  units_sold  unit_price   sales
0  2024-11-03      1001         262        23.0       29.55  679.65
1  2022-05-14      1005         256        20.0       25.32  506.40
2  2023-11-07      1008         245        25.0       31.58  789.50
3  2024-08-20      1000         232        19.0       25.91  492.29
4  2023-03-05      1001         255        28.0       22.45  628.60

In [26]:
# Convert to datetime if needed
df_filtered['date'] = pd.to_datetime(df_filtered['date'])

# Extract month number
df_filtered['Month'] = df_filtered['date'].dt.month

# Group and summarise sales
monthly_sales = df_filtered.groupby('Month')['sales'].sum()
monthly_sales

<ipython-input-26-62082ee4db88>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['date'] = pd.to_datetime(df_filtered['date'])
<ipython-input-26-62082ee4db88>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Month'] = df_filtered['date'].dt.month

Month
1     397589.77
2     338824.17
3     382800.10
4     398741.10
5     384460.97
6     357337.15
7     397114.00
8     406638.18
9     373164.15
10    386433.38
11    384602.80
12    375232.23
Name: sales, dtype: float64